
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ChakraBaseProvider
} from '@chakra-ui/react'



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flashpoint Fuel",
  description: "Generated by Wasif",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">   

      <body className={inter.className}> <ChakraBaseProvider>{children} </ChakraBaseProvider></body>   

    </html>
  );
}
